name: deriv_api
description: A Dart API Client for the Deriv API.
version: 1.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
  json_serializable: ^6.2.0
  equatable: ^2.0.3
  mockito: ^5.0.17

dev_dependencies:
  build_runner: ^2.0.5
  test: any
